### ISSUE TITLE
tiny: linebreaker publish no info using \listfile

### ISSUE THREAD

**Issue by hpvd** [michal-h21/linebreaking#8]
When using `\listfiles` command at the very beginning of the main file,
most latex package publish some details to logfile, like version used and a summary what the package does.
Linebreaker package doesn't yet (v1c), please see attachment.
-> In some cases, supporting this would be handy for debugging...

![2023-03-28_22h29_05](https://user-images.githubusercontent.com/5681880/228360847-fb394cf4-df8a-4d44-87b5-f8ef9d1d67ac.png)

**Comment by michal-h21** [comment]
The CTAN version doesn't, but I've added it in the development version, see this commit: 8e36496

**Comment by hpvd** [comment]
perfect!
I saw this commit but thought the ctan version was released after that. Was only reading packed 27.03.2023 but this was the date of miktex package I suppose...
Sorry for raising unnecessary effort.
